---
apiVersion: v1
kind: Template
labels:
  template: 'grad-program_management-api-template'
metadata:
  name: 'grad-program_management-api-template'
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: grad-program_management-api-pipeline
      name: grad-program_management-api-pipeline
      namespace: wbmfsf-tools
    spec:
      source:
        git:
          ref: master
          uri: 'https://github.com/bcgov/EDUC-GRAD-PROGRAM-MANAGEMENT-API'
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: tools/jenkins/Jenkinsfile-api
